jd_scripts:
        image: lxk0301/jd_scripts
        container_name: jd_scripts
        restart: always
        volumes:
                - ./logs:/scripts/logs
        tty: true
        environment:
                - REPO_URL=git@gitee.com:lxk0301/jd_scripts.git